### ISSUE TITLE
nginx not running via SMF?

### ISSUE THREAD

**Issue by doc** [datasets-at/mi-jenkins#2]
Hi There. Firstly thanks for creating this dataset! 

I've just spun up a container based on this dataset and cannot seem to connect to port 80 as there is no nginx process running. In looking through your source here I don't see where you are importing an nginx config into smf. Am I missing something? 

Thanks!

**Comment by MerlinDMC** [comment]
nginx gets enable in the zoneinit process: https://github.com/datasets-at/mi-jenkins/blob/master/copy/var/zoneinit/includes/32-nginx.sh

It might take a while or fail to reach that point - you should be able to login via zlogin and take a look at the zoneinit log.

**Comment by doc** [comment]
Ok thanks, will have a look!

**Comment by doc** [comment]
Ok had a peek at - for some reason the zoneinit process didn't complete properly on my container. The nginx package got installed fine but I had to run svcadm enable manually to start the service. I'm assuming that this is not expected behaviour?

**Comment by MerlinDMC** [comment]
Can you pastebin/gist/whatsoever the `/var/svc/log/system-zoneinit\:default.log` of that zone? ... That should show where it did break.

**Comment by doc** [comment]
You bet, https://gist.github.com/doc/e155116d6184487d26be

**Comment by MerlinDMC** [comment]
That makes it clear :)

The zoneinit script does try to get the set hostname from metadata to put it into the nginx server configuration. If you didn't set a hostname in your JSON when creating the zone this will result in smth like `server_name ;` in the nginx configuration which results in a syntax error - nginx exits non-zero and the zoneinit process breaks.

So ... as a workaround set `"hostname": "something"` in the JSON you feed to vmadm.

I'll see to get an update version out that will fallback to some (shitty) default for the hostname if it's not set so this will not break anymore.

**Comment by MerlinDMC** [comment]
Actually I'm wrong with the nginx config ... but the missing hostname is still the source of the problem ;)

**Comment by doc** [comment]
@MerlinDMC makes sense! I just did some testing and new container is working properly with the hostname set. Also noticed on broken container zoneinit service is in maintenance whereas new one both zoneinit & nginx service is enabled and online. 

Thanks much for your help working through this.

**Comment by MerlinDMC** [comment]
@doc There is an updated image pushed as `e2e32142-526a-11e5-b236-9bdae32772a0` on datasets.at now - feel free to use that (also includes an updated version of jenkins)
